"😀  I Feel Fine",
"🥲  Hanging on",
"💞  Feeling Romantic",
"🙂  Feeling Numb",
"😉  Feeling Flirty",
"😌  I’m upto no good",
"😍  Life is Beautiful",
"🥰  Feeling Loved",
"😘  Feeling Generous",
"😛  Feeling Mischievous",
"🤪  Feeling Goofy",
"🧐  Feeling Suspicious",
"🤓  Feeling Geeky",
"😎  Feeling Cool",
"🥳  Feeling Celebratory",
"😏  Feeling Sarcastic",
"😒  Feeling Annoyed",
"😞  Feeling Disappointed",
"😔  Feeling Betrayed",
"😟  Feeling Surprised",
"☹️  Feeling Sad",
"🥺  Feeling Sensitive",
"😤  Feeling Aggressive",
"🤤  Feeling Horny",
"😵  Feeling Shocked",
"🤐  Feeling Tongue Tied",
"🥴  Feeling Anxious",
"🤢  Feeling Disgusted",
"🤒  Feeling Sick",
"😈  Feeling Naughty",
"🤡  Feeling like a joke",
"💩  Feeling like shit",
"🍿😎  Feel like Netflix",